version: '3'
services:
  sophia:
    build: .
    command: flask run
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      - MYSQL_USER=sophia
      - MYSQL_PASSWORD=sophia
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul

    volumes:
      - ./:/app
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
  mysql_server:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password

    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci    

    volumes:
      -./data/mysql:/var/lib/mysql
  library_db:
    image: mysql